# Generated by Django 4.2 on 2023-12-29 05:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_user_uuid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "회원", "verbose_name_plural": "회원 목록"},
        ),
    ]
