# Generated by Django 4.2 on 2024-01-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_alter_user_active_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="active_level",
            field=models.CharField(
                choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4"), ("5", "5")],
                default="level 1",
                max_length=29,
            ),
        ),
    ]
