# Generated by Django 4.2 on 2024-01-09 00:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0010_alter_user_active_level"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="privacypolicy",
            options={
                "verbose_name": "개인정보 처리방침",
                "verbose_name_plural": "개인정보 처리방침 목록",
            },
        ),
    ]
