# Generated by Django 4.2 on 2024-01-02 08:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Nutrient",
            fields=[
                (
                    "food_name",
                    models.CharField(
                        db_column="Food_Name",
                        max_length=45,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("weight_g", models.FloatField(blank=True, null=True)),
                (
                    "energy_kcal",
                    models.FloatField(blank=True, db_column="Energy_kcal", null=True),
                ),
                ("carbs_g", models.FloatField(blank=True, null=True)),
                ("sugar_g", models.FloatField(blank=True, null=True)),
                ("fat_g", models.FloatField(blank=True, null=True)),
                ("protein_g", models.FloatField(blank=True, null=True)),
                ("nat_mg", models.FloatField(blank=True, null=True)),
                ("col_mg", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "nutrient",
            },
        ),
        migrations.CreateModel(
            name="Usermealevaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.UUIDField(default=uuid.uuid4)),
                ("meal_date", models.DateField(blank=True, null=True)),
                ("sys_config", models.FloatField(blank=True, null=True)),
                ("sum_carb", models.FloatField(blank=True, null=True)),
                ("sum_sugar", models.FloatField(blank=True, null=True)),
                ("sum_protein", models.FloatField(blank=True, null=True)),
                ("sun_fat", models.FloatField(blank=True, null=True)),
                ("meal_evaluation", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "usermealevaluation",
            },
        ),
        migrations.CreateModel(
            name="Usermeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.UUIDField(default=uuid.uuid4)),
                ("meal_type", models.TextField(blank=True, null=True)),
                ("meal_date", models.DateField(blank=True, null=True)),
                ("image_link", models.TextField(blank=True, null=True)),
                (
                    "food_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usermeals",
                        to="Meal_Date.nutrient",
                    ),
                ),
            ],
            options={
                "db_table": "usermeal",
            },
        ),
    ]
