# Generated by Django 4.2 on 2024-01-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Meal_Date", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nutrient",
            name="food_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usermeal",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="usermealevaluation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
