# Generated by Django 4.2 on 2024-01-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meal_Date', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeal',
            name='meal_serving',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
