# Generated by Django 4.2 on 2024-01-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Meal_Date", "0004_alter_usermeal_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermeal",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
