# Generated by Django 4.2 on 2024-01-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Meal_Date", "0005_alter_usermeal_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermeal",
            name="id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="usermealevaluation",
            name="id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
