# Generated by Django 4.2 on 2024-01-03 02:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("Meal_Date", "0006_alter_usermeal_id_alter_usermealevaluation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermeal",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="usermealevaluation",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
