# Generated by Django 4.2 on 2024-01-03 05:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Meal_Date", "0008_remove_nutrient_food_id_alter_usermeal_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
