# Generated by Django 4.2 on 2024-01-03 06:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Meal_Date", "0009_delete_customuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermealevaluation",
            name="sys_config",
        ),
    ]
