# Generated by Django 4.2 on 2024-01-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Meal_Date", "0011_rename_sun_fat_usermealevaluation_sum_fat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermeal",
            name="image_link",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
