# Generated by Django 4.2 on 2024-01-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Meal_Date", "0012_alter_usermeal_image_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermealevaluation",
            name="sum_col",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usermealevaluation",
            name="sum_nat",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
