# Generated by Django 4.2 on 2024-01-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Meal_Date", "0014_rename_image_link_usermeal_imagelink_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermeal",
            name="meal_serving",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
