# Generated by Django 4.2 on 2024-01-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Meal_Date", "0015_usermeal_meal_serving"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermeal",
            name="meal_serving",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
