# Generated by Django 4.2 on 2024-01-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Meal_Date", "0016_alter_usermeal_meal_serving"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermeal",
            name="imagelink",
            field=models.ImageField(max_length=2000, upload_to="images/"),
        ),
    ]
