# Generated by Django 4.2 on 2024-01-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Meal_Date', '0002_usermeal_meal_serving'),
        ('Meal_Date', '0017_alter_usermeal_imagelink'),
    ]

    operations = [
    ]
