# Generated by Django 4.2 on 2024-01-07 04:57

import Meal_Date.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Meal_Date", "0017_alter_usermeal_imagelink"),
    ]

    operations = [
        migrations.CreateModel(
            name="Imagesave",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "imagelink",
                    models.ImageField(
                        max_length=3000, upload_to=Meal_Date.models.get_image_filename
                    ),
                ),
            ],
            options={
                "db_table": "Imagesave",
            },
        ),
        migrations.AlterField(
            model_name="usermeal",
            name="imagelink",
            field=models.ImageField(
                max_length=3000, upload_to=Meal_Date.models.get_image_filename
            ),
        ),
    ]
