# Generated by Django 4.2 on 2024-01-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meal_Date', '0018_merge_20240106_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeal',
            name='imagelink',
            field=models.ImageField(max_length=3000, upload_to='images/'),
        ),
    ]
