# Generated by Django 4.2 on 2024-01-07 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Meal_Date', '0018_imagesave_alter_usermeal_imagelink'),
        ('Meal_Date', '0019_alter_usermeal_imagelink'),
    ]

    operations = [
    ]
