# Generated by Django 4.2 on 2023-12-29 02:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="질문")),
                ("content", models.TextField(verbose_name="답변")),
            ],
            options={
                "verbose_name": "자주 묻는 질문",
                "verbose_name_plural": "자주 묻는 질문들",
            },
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "posted_on",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="게시 날짜"
                    ),
                ),
            ],
            options={
                "verbose_name": "공지사항",
                "verbose_name_plural": "공지사항들",
            },
        ),
    ]
