# Generated by Django 4.2 on 2023-12-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                (
                    "image",
                    models.ImageField(upload_to="cardnews_images/", verbose_name="이미지"),
                ),
            ],
            options={
                "verbose_name": "카드뉴스",
                "verbose_name_plural": "카드뉴스들",
            },
        ),
    ]
