# Generated by Django 4.2 on 2024-01-09 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("board", "0003_cardnews_link"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cardnews",
            options={"verbose_name": "카드뉴스", "verbose_name_plural": "카드뉴스 목록"},
        ),
        migrations.AlterModelOptions(
            name="faq",
            options={"verbose_name": "자주 묻는 질문", "verbose_name_plural": "자주 묻는 질문 목록"},
        ),
        migrations.AlterModelOptions(
            name="notice",
            options={"verbose_name": "공지사항", "verbose_name_plural": "공지사항 목록"},
        ),
        migrations.CreateModel(
            name="Ask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="ask_images/",
                        verbose_name="사진",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="문의 날짜"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="회원",
                    ),
                ),
            ],
            options={
                "verbose_name": "1대1 문의",
                "verbose_name_plural": "1대1 문의 목록",
            },
        ),
    ]
