# Generated by Django 4.2 on 2024-01-09 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("board", "0004_alter_cardnews_options_alter_faq_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ask",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asks",
                to=settings.AUTH_USER_MODEL,
                to_field="uuid",
                verbose_name="회원",
            ),
        ),
    ]
